# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: BrowserStack 1to1 Devices

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filter for tests'
        required: true
        default: '@Smoke and @Automated'
      device:
        description: 'Select the device to test'
        required: true
        type: choice
        options:
          - Samsung Galaxy A11
          - Samsung Galaxy A51
          - Motorola Moto G71 5G
          - Google Pixel 7 Pro
          - Xiaomi Redmi Note 11
          - Huawei P30
          - Oppo Reno 6
        default: 'Samsung Galaxy A11'

jobs:
  test:
    runs-on: ubuntu-22.04
    container: crowdar/lippia:3.3.0.0-jdk17
    environment: Automation
    env:
      BSUSER: ${{ secrets.BSUSER }}
      AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
      BSDEVICE: ${{ github.event.inputs.device }}
      BSAPP: ${{ secrets.BSAPP }}
      LTM_GENERAL: ${{ secrets.LTM_GENERAL }}
      LTM_GENERAL_PASS: ${{ secrets.LTM_GENERAL_PASS }}

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Configuring JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Android version based on selected device
        run: |
          if [[ "${{ github.event.inputs.device }}" == "Samsung Galaxy A11" ]]; then
            echo "BSOS=10" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.device }}" == "Samsung Galaxy A51" ]]; then
            echo "BSOS=10" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.device }}" == "Motorola Moto G71 5G" ]]; then
            echo "BSOS=11" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.device }}" == "Google Pixel 7 Pro" ]]; then
            echo "BSOS=13" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.device }}" == "Xiaomi Redmi Note 11" ]]; then
            echo "BSOS=11" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.device }}" == "Huawei P30" ]]; then
            echo "BSOS=9" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.device }}" == "Oppo Reno 6" ]]; then
            echo "BSOS=11" >> $GITHUB_ENV
          fi

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings>
          <mirrors>
            <mirror>
                <id>central</id>
                <url>https://repo.maven.apache.org/maven2</url>
                <mirrorOf>*</mirrorOf>
            </mirror>
          </mirrors>
          </settings>' > ~/.m2/settings.xml

      - name: List directories to verify path
        run: ls -al ~/.m2

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checking Maven dependencies
        run: mvn dependency:resolve

      - name: Setting environment variable
        run: echo "COMBINED_FILTER=${{ github.event.inputs.filter }}" >> $GITHUB_ENV

      - name: Debugging environment variables
        run: |
          echo "BSDEVICE: $BSDEVICE"
          echo "BSOS: $BSOS"
          echo "BSUSER: $BSUSER"
          echo "AUTHTOKEN: $AUTHTOKEN"
          echo "BSAPP: $BSAPP"
          echo "LTM_GENERAL: $LTM_GENERAL"
          echo "LTM_GENERAL_PASS: $LTM_GENERAL_PASS"

      - name: Running Maven clean test
        run: |
          echo "Running tests with filter: '$COMBINED_FILTER' on device: '$BSDEVICE' with OS version: '$BSOS'"
          mvn clean test -Dcrowdar.cucumber.filter="'$COMBINED_FILTER'" \
                         -Denv.BSDEVICE="${{ github.event.inputs.device }}" \
                         -Denv.BSOS="$BSOS" \
                         -DTEST_MANAGER_RUN_NAME="AUTO-${{ github.event.inputs.device }}-${{ github.event.inputs.filter }}" \
                         -DLTM_GENERAL="${{ secrets.LTM_GENERAL }}" \
                         -DLTM_GENERAL_PASS="${{ secrets.LTM_GENERAL_PASS }}" \
                         -PBrowserStack -PAndroid -U
        shell: bash

      - name: Uploading test reports
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results
          path: target/reports/

      - name: Uploading HTML test report
        uses: actions/upload-artifact@v4.3.4
        with:
          name: html-report
          path: target/cucumber-reports/cucumber-html-report/*.html


      - name: Uploading surefire test reports
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results-surefire
          path: target/surefire-reports/

